### ISSUE TITLE
你好，请教交流一下

### ISSUE THREAD

**Issue by leochen-g** [acrazing/dbapi#3]
你好，请问一下，按照你目前的接口来看的话，批量操作这一块是无法实现的吧，还有针对多页的评论不知道自己在第几页，这个也是无法自动循环找到的吧？我现在在做一个js的豆瓣批量操作程序，刚好看到你的这篇文章，想交流一下，如果可以的话，能加一下微信么？我的是CG12104410

**Comment by acrazing** [comment]
嗯, 分析 html 找评论的话就只能一页一页的找了
