### ISSUE TITLE
Why 'Authorization failed' during login?

### ISSUE THREAD

**Issue by ClaireJL** [acrazing/dbapi#5]
Hello, when I run 
`dbapi login <usr_email> <usr_pwd>`
I always get the following error:

> Traceback (most recent call last):
>   File "/Users/clairel/anaconda3/bin/dbapi", line 10, in <module>
>     sys.exit(main())
>   File "/Users/clairel/anaconda3/lib/python3.7/site-packages/dbapi/cli.py", line 82, in main
>     print(json.dumps(method(*args), indent=2, default=default))
>   File "/Users/clairel/anaconda3/lib/python3.7/site-packages/dbapi/base.py", line 224, in login
>     raise Exception('Authorization failed for <%s>: %s' % (username, r1.url))
> Exception: Authorization failed for <my_email_address>: https://accounts.douban.com/passport/login

I'm sure that my account information is correct. Do you have any idea why this is happening? Thanks a lot!

**Comment by acrazing** [comment]
emm, this is caused by douban changing the API, this project is outdated. PR is welcome~
